### PR TITLE
TransactionDb Support

### PR DESCRIPTION
**Pull request by srehm**
Hello,

I have been working on a project lately that needed Transaction support so I went ahead and implemented it. The implementation is based in rev. 2e64f45 of rocksdb. I think this feature might be useful to others as well. I would be glad if you decide to merge it into the upstream repository.

Regards,
Stefan

### CODE REVIEW

**Comment by mkosieradzki** [comment]
@srehm Thanks a lot.
@warrenfalk Any chance for merge?

**Comment by mkosieradzki** [comment]
@srehm I have tried to build your branch and there are some problems with merge (a lot of duplicate symbols in Native.Raw.cs)

**Comment by warrenfalk** [comment]
Yes, I'm happy to merge in support for TransactionDb.  This particular PR isn't a trivial pull because it:

1. updates to a rocksdb version which isn't actually released yet and
2. implements the transaction db changes all in the same commit and
3. updates the rocksdb-sharp bindings from from an older version to that newer version thus implementing several api functions a second time in the history but not in the same exact way, thereby making the merge difficult.  Although a merge has been attempted, if your experience is correct, then it might not be correct and might need some work, and lastly
4. when new apis are implemented, I prefer to ensure that they are added at least to the functional test script just to make sure that at least the most rudimentary use of them stays functional and that there is an example of their usage.

The combination of these above things together is what makes this difficult to just merge in the way it is now.  But if the TransactionDb support itself is solid, then I'm happy to take it provided that the C api endpoints in use are in a released version of rocksdb.

**Comment by mkosieradzki** [comment]
@warrenfalk Thanks a lot for you response. I see your points, I am trying to deep dive into this project and maybe add some contributions. I am interested in TransactionDb support as well.

Currently I am trying to understand why there is "native" folder instead of "runtimes" and whether it is feasible to use the same approach as used in LibUV... I believe you have already gave it at shot.

However back to the main topic:
It would be really nice if @srehm would be so kind to improve his PR.

**Comment by tmdoit-zz** [comment]
Any updates on this topic? @warrenfalk are you planning to add this feature?

**Pull request closed without merging**
